### PR TITLE
Expose details about Stripe failures

### LINKED ISSUE #112: Error handling: Status text missing for the "insufficient funds" case
Trying to buy storage-time with a card with insufficient funds currently results in a "400" HTTP error without any further information.

Having a `statusText` to display ([frontend code here](https://whetstone.private.storage/privatestorage/privatestorageweb/-/merge_requests/91/diffs#b3c4f1c8ecd2f24606b1dab692e058e50447a08e_48_48)) would be helpful.

Screenshot by Eric:
payment processing error
 
I look at [Monitoring for around that time](https://monitoring.privatestorage.io/d/Payments/payments?orgId=1&from=1646130848091&to=1646131245552) and it seems it was indeed "insufficient funds":
```
2022-03-01 10:07:51  POST /v1/stripe/charge
2022-03-01 10:07:51  "Stripe createCharge failed:"
2022-03-01 10:07:51  "Your card has insufficient funds."
```
The related error on the server also has no statusText:
```
2022-03-01 10:07:51	
  Status: 400  1.732255581s
```

Maybe related to #50.
Maybe already fixed by #111.

### PR DESCRIPTION
**Pull request by exarkun**
Fixes #112 

This puts the Stripe details into the JSON body and makes sure the standard error phrase is always present.

### CODE REVIEW

File: test/Stripe.hs [hunk 1]
```diff
@@ -163,15 +170,43 @@ chargeTests =
...
+    withFakeStripe (return (chargeFailed cardError)) $ \stripeConfig -> do
+      let amount = 650
+      let currency = USD
+      db <- memory
+      (Left (ServerError code phrase body _)) <- runExceptT . runHandler' $ charge stripeConfig db (Charges token voucher amount currency)
+      assertEqual "The result is an error" 400 code
+      assertEqual "The HTTP phrase matches the code" "Bad Request" phrase
+      -- The `cardError` is for a card expired error.
+      assertEqual "The JSON body includes the reason"
+        (Just $ Failure "Stripe charge didn't succeed: Your card is expired.") (decode body)
```
Comment (hacklschorsch) [inline test/Stripe.hs:198]: > Your card is expired.

Is this correct?  I thought `cardError` would indicate a whole lot of different things, Above, your own comment says:

>       -- "Card errors are the most common type of error you should expect to
>       -- handle. They result when the user enters a card that can't be charged
>       -- for some reason."


----

Above (Line 186, `let err = errorForStripe errorType ( concat [ "Stripe charge didn't succeed: ", msg ])`) very much looks like the Stripe upstream error message is propagated, which is what we want.
So I read this as "the test fixture `cardError` is a card expired error" and not as "`cardError` will result in a message that says the card is expired".

**Review by hacklschorsch — APPROVED** [review]
Little bit of confusion left about the `cardError` in the test.

Besides, as always, excellent work. Thank you for staying on it.  This is a big improvement to the check-out process IMHO.

File: test/Stripe.hs (hunk 1 above)
Comment (exarkun) [reply test/Stripe.hs:198]: Yep - see https://github.com/PrivateStorageio/PaymentServer/pull/113/files#diff-c44673a5714663692552825bf3666ca8557cf8217b71f349cae6aa1c93e2c10dR53-R62

In the comment I just meant that this specific `cardError` value that we have is for that case.  You could have a different card error for another case (but the test suite doesn't have one).
